from __future__ import annotations

from pathlib import Path

import pytest

from bench.gsm8k_paper_utils import load_gsm8k
from scripts.run_gsm8k_selector_components_pilot import METHODS, SELECTORS, shared_patternkv_config


def test_gsm8k_dataset_contract():
    path = Path("datasets/gsm8k/gsm8k_test.jsonl")
    rows = load_gsm8k(path)
    assert len(rows) == 1319
    assert [int(r["problem_id"]) for r in rows[:3]] == [0, 1, 2]
    assert int(rows[-1]["problem_id"]) == 1318


def test_component_pilot_method_registration():
    assert METHODS == ("importance_only_v4_25", "error_only_v4_25", "causal_v4_25")
    assert SELECTORS["importance_only_v4_25"] == "importance_only_v4"
    assert SELECTORS["error_only_v4_25"] == "error_only_v4"
    assert SELECTORS["causal_v4_25"] == "causal_v4"


def test_component_pilot_budget_is_exact_25_percent():
    cfg = shared_patternkv_config()
    assert cfg["k_bits"] == 2
    assert cfg["base_v_bits"] == 2
    assert cfg["selected_v_bits"] == 4
    assert cfg["patternkv_v4_budget_fraction"] == 0.25
    assert cfg["patternkv_cache_path"] == "segmented"
    assert cfg["patternkv_cache_mode"] == "segmented_rolling"


def test_gpu_policy_uses_user_selected_idle_gpus_not_original_hardcode():
    selected = {"1", "4"}
    forbidden = {"2", "3"}
    assert len(selected) == 2
    assert not selected & forbidden
    assert selected != {"0", "1"}


def test_existing_manifest_if_present_is_exact_and_matched():
    manifest = Path("reports/gsm8k_selector_components_pilot_v1/pilot_manifest.json")
    if not manifest.exists():
        pytest.skip("pilot manifest is generated by prepare gate")
    import json

    data = json.loads(manifest.read_text(encoding="utf-8"))
    rows = data["rows"]
    pids = [int(r["problem_id"]) for r in rows]
    assert len(rows) == 50
    assert len(set(pids)) == 50
    assert sum(1 for r in rows if r["stratum"] == "UNIFORM_RANDOM") == 25
    assert sum(1 for r in rows if r["stratum"] == "LENGTH_PROXY_ACTIVATION_ENRICHED") == 25
    assert data["gpu_policy"]["selected_physical_gpus"] == ["1", "4"]
    assert not set(data["gpu_policy"]["selected_physical_gpus"]) & set(data["gpu_policy"]["forbidden_physical_gpus"])
